# Generated by Django 5.0.9 on 2025-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_alter_subscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': [('advance', 'Advanced Pro Plan'), ('pro', 'Pro Perm'), ('basic', 'Basic Perm'), ('basic_ai', 'Basic AI Perm')], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
