# Generated by Django 5.0.9 on 2025-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_group_subscription_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advance', 'pro', 'basic', 'basic_ai'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
